services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html


  php-fpm:
    container_name: php-fpm
    build: ../online-shop/docker
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  postgres:
      image: postgres:latest
      volumes:
        - ./docker/postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_HOST=${DB_HOST}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - 54321:5432
